* Entity image #0
* Shift #0
         hex   000000    ; 
         hex   400000    ;       *              
         hex   430000    ; **    *              
         hex   630100    ; **   ***             
         hex   600100    ;      ***             
         hex   300300    ;     ** **            
         hex   2c0d00    ;   ** * * **          
         hex   2a1500    ;  * * * * * *         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   000100    ;        *             
         hex   060100    ;  **    *             
         hex   460300    ;  **   ***            
         hex   400300    ;       ***            
         hex   600600    ;      ** **           
         hex   581a00    ;    ** * * **         
         hex   542a00    ;   * * * * * *        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   000200    ;         *            
         hex   000200    ;         *            
         hex   400500    ;       ** *           
         hex   400500    ;       ** *           
         hex   400d00    ;       ** **          
         hex   303500    ;     ** * * **        
         hex   285500    ;    * * * * * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   000400    ;          *           
         hex   000400    ;          *           
         hex   000b00    ;        ** *          
         hex   000b00    ;        ** *          
         hex   001b00    ;        ** **         
         hex   606a00    ;      ** * * **       
         hex   502a01    ;     * * * * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   000800    ;           *          
         hex   00080c    ;           *     **   
         hex   001c0c    ;          ***    **   
         hex   001c00    ;          ***         
         hex   003600    ;         ** **        
         hex   405501    ;       ** * * **      
         hex   205502    ;      * * * * * *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   001000    ;            *         
         hex   001018    ;            *     **  
         hex   003818    ;           ***    **  
         hex   003800    ;           ***        
         hex   006c00    ;          ** **       
         hex   002b03    ;        ** * * **     
         hex   402a05    ;       * * * * * *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   002000    ;             *        
         hex   006001    ;             ***      
         hex   007001    ;            ****      
         hex   007000    ;            ***       
         hex   005801    ;           ** **      
         hex   005606    ;         ** * * **    
         hex   00550a    ;        * * * * * *   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #1
* Shift #0
         hex   000000    ; 
         hex   400000    ;       *              
         hex   400000    ;       *              
         hex   400000    ;       *              
         hex   540a00    ;   * * * * *          
         hex   2a1500    ;  * * * * * *         
         hex   500200    ;     * * *            
         hex   080400    ;    *     *           
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   000100    ;        *             
         hex   000100    ;        *             
         hex   000100    ;        *             
         hex   281500    ;    * * * * *         
         hex   542a00    ;   * * * * * *        
         hex   200500    ;      * * *           
         hex   100800    ;     *     *          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   000200    ;         *            
         hex   000200    ;         *            
         hex   000200    ;         *            
         hex   703a00    ;     *** * ***        
         hex   084500    ;    *   * *   *       
         hex   400a00    ;       * * *          
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   000400    ;          *           
         hex   000400    ;          *           
         hex   000400    ;          *           
         hex   607500    ;      *** * ***       
         hex   100a01    ;     *   * *   *      
         hex   001500    ;        * * *         
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   000800    ;           *          
         hex   000800    ;           *          
         hex   000800    ;           *          
         hex   706b07    ;     ***** * *****    
         hex   001400    ;          * *         
         hex   002a00    ;         * * *        
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   001000    ;            *         
         hex   001000    ;            *         
         hex   001000    ;            *         
         hex   60570f    ;      ***** * *****   
         hex   002800    ;           * *        
         hex   005400    ;          * * *       
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   002000    ;             *        
         hex   002000    ;             *        
         hex   002606    ;         **  *  **    
         hex   002909    ;        *  * * *  *   
         hex   405010    ;       *    * *    *  
         hex   002801    ;           * * *      
         hex   000402    ;          *     *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #2
* Shift #0
         hex   000000    ; 
         hex   7c0000    ;   *****              
         hex   400f00    ;       *****          
         hex   400000    ;       *              
         hex   400000    ;       *              
         hex   4c0c00    ;   **  *  **          
         hex   521200    ;  *  * * *  *         
         hex   612100    ; *    ***    *        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   780100    ;    *****             
         hex   001f00    ;        *****         
         hex   000100    ;        *             
         hex   000100    ;        *             
         hex   181900    ;    **  *  **         
         hex   242500    ;   *  * * *  *        
         hex   424300    ;  *    ***    *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   400300    ;       ***            
         hex   000e00    ;         ***          
         hex   000200    ;         *            
         hex   000200    ;         *            
         hex   3c7201    ;   ****  *  ****      
         hex   400a00    ;       * * *          
         hex   000700    ;        ***           
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   000700    ;        ***           
         hex   001c00    ;          ***         
         hex   000400    ;          *           
         hex   000400    ;          *           
         hex   786403    ;    ****  *  ****     
         hex   001500    ;        * * *         
         hex   000e00    ;         ***          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   007801    ;           *****      
         hex   400f00    ;       *****          
         hex   100804    ;     *     *     *    
         hex   200802    ;      *    *    *     
         hex   404901    ;       **  *  **      
         hex   002a00    ;         * * *        
         hex   001c00    ;          ***         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   007003    ;            *****     
         hex   001f00    ;        *****         
         hex   201008    ;      *     *     *   
         hex   401004    ;       *    *    *    
         hex   001303    ;        **  *  **     
         hex   005400    ;          * * *       
         hex   003800    ;           ***        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   006001    ;             ***      
         hex   003800    ;           ***        
         hex   002000    ;             *        
         hex   002000    ;             *        
         hex   40271e    ;       ****  *  ****  
         hex   002801    ;           * * *      
         hex   007000    ;            ***       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #3
* Shift #0
         hex   000000    ; 
         hex   7f7f00    ; **************       
         hex   014000    ; *            *       
         hex   014000    ; *            *       
         hex   2b5500    ; ** * * * * * *       
         hex   7e3f00    ;  ************        
         hex   542a00    ;   * * * * * *        
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   7e7f01    ;  **************      
         hex   020001    ;  *            *      
         hex   020001    ;  *            *      
         hex   562a01    ;  ** * * * * * *      
         hex   7c7f00    ;   ************       
         hex   285500    ;    * * * * * *       
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   7c7f03    ;   **************     
         hex   040002    ;   *            *     
         hex   2c5502    ;   ** * * * * * *     
         hex   2c5502    ;   ** * * * * * *     
         hex   787f01    ;    ************      
         hex   502a01    ;     * * * * * *      
         hex   502a01    ;     * * * * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   787f07    ;    **************    
         hex   080004    ;    *            *    
         hex   582a05    ;    ** * * * * * *    
         hex   582a05    ;    ** * * * * * *    
         hex   707f03    ;     ************     
         hex   205502    ;      * * * * * *     
         hex   205502    ;      * * * * * *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   707f0f    ;     **************   
         hex   100008    ;     *            *   
         hex   502a0d    ;     * * * * * * **   
         hex   502a0d    ;     * * * * * * **   
         hex   607f07    ;      ************    
         hex   205502    ;      * * * * * *     
         hex   205502    ;      * * * * * *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   607f1f    ;      **************  
         hex   200010    ;      *            *  
         hex   20551a    ;      * * * * * * **  
         hex   20551a    ;      * * * * * * **  
         hex   407f0f    ;       ************   
         hex   402a05    ;       * * * * * *    
         hex   402a05    ;       * * * * * *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   407f3f    ;       ************** 
         hex   400020    ;       *            * 
         hex   400020    ;       *            * 
         hex   402a35    ;       * * * * * * ** 
         hex   007f1f    ;        ************  
         hex   00550a    ;        * * * * * *   
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #4
* Shift #0
         hex   000000    ; 
         hex   700700    ;     ******           
         hex   2c1a00    ;   ** *  * **         
         hex   2a2a00    ;  * * *  * * *        
         hex   2a2a00    ;  * * *  * * *        
         hex   2a2a00    ;  * * *  * * *        
         hex   2c1a00    ;   ** *  * **         
         hex   700700    ;     ******           
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   600f00    ;      ******          
         hex   583400    ;    ** *  * **        
         hex   545400    ;   * * *  * * *       
         hex   545400    ;   * * *  * * *       
         hex   545400    ;   * * *  * * *       
         hex   583400    ;    ** *  * **        
         hex   600f00    ;      ******          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   401f00    ;       ******         
         hex   306900    ;     ** *  * **       
         hex   282901    ;    * * *  * * *      
         hex   282901    ;    * * *  * * *      
         hex   282901    ;    * * *  * * *      
         hex   306900    ;     ** *  * **       
         hex   401f00    ;       ******         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   003f00    ;        ******        
         hex   605201    ;      ** *  * **      
         hex   505202    ;     * * *  * * *     
         hex   505202    ;     * * *  * * *     
         hex   505202    ;     * * *  * * *     
         hex   605201    ;      ** *  * **      
         hex   003f00    ;        ******        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   007e00    ;         ******       
         hex   605b07    ;      **** ** ****    
         hex   505a0a    ;     * * * ** * * *   
         hex   505a0a    ;     * * * ** * * *   
         hex   505a0a    ;     * * * ** * * *   
         hex   605b07    ;      **** ** ****    
         hex   007e00    ;         ******       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   007c01    ;          ******      
         hex   40370f    ;       **** ** ****   
         hex   203515    ;      * * * ** * * *  
         hex   203515    ;      * * * ** * * *  
         hex   203515    ;      * * * ** * * *  
         hex   40370f    ;       **** ** ****   
         hex   007c01    ;          ******      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   007803    ;           ******     
         hex   006f1e    ;        **** ** ****  
         hex   406a2a    ;       * * * ** * * * 
         hex   406a2a    ;       * * * ** * * * 
         hex   406a2a    ;       * * * ** * * * 
         hex   006f1e    ;        **** ** ****  
         hex   007803    ;           ******     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #5
* Shift #0
         hex   000000    ; 
         hex   787f00    ;    ***********       
         hex   186000    ;    **       **       
         hex   7e6000    ;  ******     **       
         hex   435500    ; **    ** * * *       
         hex   665400    ;  **  **  * * *       
         hex   005400    ;          * * *       
         hex   005400    ;          * * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   707f01    ;     ***********      
         hex   304001    ;     **       **      
         hex   7c4101    ;   ******     **      
         hex   062b01    ;  **    ** * * *      
         hex   4c2901    ;   **  **  * * *      
         hex   002801    ;           * * *      
         hex   002801    ;           * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   607f03    ;      ***********     
         hex   600003    ;      **       **     
         hex   600003    ;      **       **     
         hex   605002    ;      **    * * *     
         hex   785302    ;    ******  * * *     
         hex   0c5602    ;   **    ** * * *     
         hex   185302    ;    **  **  * * *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   407f07    ;       ***********    
         hex   400106    ;       **       **    
         hex   400106    ;       **       **    
         hex   402105    ;       **    * * *    
         hex   702705    ;     ******  * * *    
         hex   182c05    ;    **    ** * * *    
         hex   302605    ;     **  **  * * *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   007f0f    ;        ***********   
         hex   00030c    ;        **       **   
         hex   00030c    ;        **       **   
         hex   00430a    ;        **    * * *   
         hex   40470a    ;       ****   * * *   
         hex   604c0a    ;      **  **  * * *   
         hex   40470a    ;       ****   * * *   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   007e1f    ;         ***********  
         hex   000618    ;         **       **  
         hex   000618    ;         **       **  
         hex   000615    ;         **    * * *  
         hex   000f15    ;        ****   * * *  
         hex   401915    ;       **  **  * * *  
         hex   000f15    ;        ****   * * *  
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   007c3f    ;          *********** 
         hex   000c30    ;          **       ** 
         hex   001e30    ;         ****      ** 
         hex   00332a    ;        **  **  * * * 
         hex   001e2a    ;         ****   * * * 
         hex   00002a    ;                * * * 
         hex   00002a    ;                * * * 
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #6
* Shift #0
         hex   000000    ; 
         hex   700100    ;     ****             
         hex   001e00    ;         ****         
         hex   700100    ;     ****             
         hex   0f0000    ; ****                 
         hex   700100    ;     ****             
         hex   001e00    ;         ****         
         hex   700100    ;     ****             
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   600300    ;      ****            
         hex   003c00    ;          ****        
         hex   600300    ;      ****            
         hex   1e0000    ;  ****                
         hex   600300    ;      ****            
         hex   003c00    ;          ****        
         hex   600300    ;      ****            
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   007800    ;           ****       
         hex   400700    ;       ****           
         hex   3c0000    ;   ****               
         hex   400700    ;       ****           
         hex   007800    ;           ****       
         hex   400700    ;       ****           
         hex   3c0000    ;   ****               
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   007001    ;            ****      
         hex   000f00    ;        ****          
         hex   780000    ;    ****              
         hex   000f00    ;        ****          
         hex   007001    ;            ****      
         hex   000f00    ;        ****          
         hex   780000    ;    ****              
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   001e00    ;         ****         
         hex   700100    ;     ****             
         hex   001e00    ;         ****         
         hex   006003    ;             ****     
         hex   001e00    ;         ****         
         hex   700100    ;     ****             
         hex   001e00    ;         ****         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   003c00    ;          ****        
         hex   600300    ;      ****            
         hex   003c00    ;          ****        
         hex   004007    ;              ****    
         hex   003c00    ;          ****        
         hex   600300    ;      ****            
         hex   003c00    ;          ****        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   400700    ;       ****           
         hex   007800    ;           ****       
         hex   00000f    ;               ****   
         hex   007800    ;           ****       
         hex   400700    ;       ****           
         hex   007800    ;           ****       
         hex   00000f    ;               ****   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #7
* Shift #0
         hex   000000    ; 
         hex   706300    ;     *****   **       
         hex   0f6600    ; ****    **  **       
         hex   726f00    ;  *  ******* **       
         hex   001c00    ;          ***         
         hex   021800    ;  *        **         
         hex   000600    ;         **           
         hex   020600    ;  *      **           
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   604701    ;      *****   **      
         hex   1e4c01    ;  ****    **  **      
         hex   645f01    ;   *  ******* **      
         hex   003800    ;           ***        
         hex   043000    ;   *        **        
         hex   000c00    ;          **          
         hex   040c00    ;   *      **          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   400f00    ;       *****          
         hex   3c1803    ;   ****    **  **     
         hex   483f03    ;    *  ******* **     
         hex   007000    ;            ***       
         hex   086000    ;    *        **       
         hex   001800    ;           **         
         hex   001800    ;           **         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   001f00    ;        *****         
         hex   783006    ;    ****    **  **    
         hex   107f06    ;     *  ******* **    
         hex   006001    ;             ***      
         hex   104001    ;     *        **      
         hex   003000    ;            **        
         hex   003000    ;            **        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   003e00    ;         *****        
         hex   706100    ;     ****    **       
         hex   207e0d    ;      *  ******* **   
         hex   004003    ;              ***     
         hex   000003    ;               **     
         hex   006000    ;             **       
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   007c00    ;          *****       
         hex   604301    ;      ****    **      
         hex   407c1b    ;       *  ******* **  
         hex   000007    ;               ***    
         hex   000006    ;                **    
         hex   004001    ;              **      
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   007801    ;           *****      
         hex   400733    ;       ****    **  ** 
         hex   007837    ;           ******* ** 
         hex   00000e    ;                ***   
         hex   00000c    ;                 **   
         hex   000003    ;               **     
         hex   000003    ;               **     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #8
* Shift #0
         hex   000000    ; 
         hex   7f7f00    ; **************       
         hex   516800    ; *   * *   * **       
         hex   356400    ; * * **   *  **       
         hex   116200    ; *   *   *   **       
         hex   157100    ; * * *  *   ***       
         hex   615f00    ; *    ******* *       
         hex   7f7f00    ; **************       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   7e7f01    ;  **************      
         hex   225101    ;  *   * *   * **      
         hex   6a4801    ;  * * **   *  **      
         hex   224401    ;  *   *   *   **      
         hex   2a6201    ;  * * *  *   ***      
         hex   423f01    ;  *    ******* *      
         hex   7e7f01    ;  **************      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   7c7f03    ;   **************     
         hex   440003    ;   *   *       **     
         hex   545503    ;   * * ** * * ***     
         hex   440003    ;   *   *       **     
         hex   545503    ;   * * ** * * ***     
         hex   047f02    ;   *    ******* *     
         hex   7c7f03    ;   **************     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   787f07    ;    **************    
         hex   080106    ;    *   *       **    
         hex   282b07    ;    * * ** * * ***    
         hex   080106    ;    *   *       **    
         hex   282b07    ;    * * ** * * ***    
         hex   087e05    ;    *    ******* *    
         hex   787f07    ;    **************    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   707f0f    ;     **************   
         hex   10120e    ;     *   *  *   ***   
         hex   50220c    ;     * * *   *   **   
         hex   10460c    ;     *   **   *  **   
         hex   500a0d    ;     * * * *   * **   
         hex   107c0b    ;     *    ******* *   
         hex   707f0f    ;     **************   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   607f1f    ;      **************  
         hex   20241c    ;      *   *  *   ***  
         hex   204518    ;      * * *   *   **  
         hex   200c19    ;      *   **   *  **  
         hex   20151a    ;      * * * *   * **  
         hex   207817    ;      *    ******* *  
         hex   607f1f    ;      **************  
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   407f3f    ;       ************** 
         hex   40583a    ;       *   ** * * *** 
         hex   405a3a    ;       * * ** * * *** 
         hex   40583a    ;       *   ** * * *** 
         hex   405a3a    ;       * * ** * * *** 
         hex   40702f    ;       *    ******* * 
         hex   407f3f    ;       ************** 
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #9
* Shift #0
         hex   000000    ; 
         hex   500200    ;     * * *            
         hex   700300    ;     *****            
         hex   500200    ;     * * *            
         hex   500200    ;     * * *            
         hex   500200    ;     * * *            
         hex   700300    ;     *****            
         hex   500200    ;     * * *            
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   200500    ;      * * *           
         hex   600700    ;      *****           
         hex   200500    ;      * * *           
         hex   200500    ;      * * *           
         hex   200500    ;      * * *           
         hex   600700    ;      *****           
         hex   200500    ;      * * *           
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   400a00    ;       * * *          
         hex   502a00    ;     * * * * *        
         hex   502a00    ;     * * * * *        
         hex   502a00    ;     * * * * *        
         hex   502a00    ;     * * * * *        
         hex   502a00    ;     * * * * *        
         hex   400a00    ;       * * *          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   001500    ;        * * *         
         hex   205500    ;      * * * * *       
         hex   205500    ;      * * * * *       
         hex   205500    ;      * * * * *       
         hex   205500    ;      * * * * *       
         hex   205500    ;      * * * * *       
         hex   001500    ;        * * *         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   002a00    ;         * * *        
         hex   402a01    ;       * * * * *      
         hex   502a05    ;     * * * * * * *    
         hex   503e05    ;     * * ***** * *    
         hex   502a05    ;     * * * * * * *    
         hex   402a01    ;       * * * * *      
         hex   002a00    ;         * * *        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   005400    ;          * * *       
         hex   005502    ;        * * * * *     
         hex   20550a    ;      * * * * * * *   
         hex   207d0a    ;      * * ***** * *   
         hex   20550a    ;      * * * * * * *   
         hex   005502    ;        * * * * *     
         hex   005400    ;          * * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   002801    ;           * * *      
         hex   002a05    ;         * * * * *    
         hex   007a05    ;         * ***** *    
         hex   002a05    ;         * * * * *    
         hex   007a05    ;         * ***** *    
         hex   002a05    ;         * * * * *    
         hex   002801    ;           * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #10
* Shift #0
         hex   000000    ; 
         hex   7f3f00    ; *************        
         hex   0b3400    ; ** *     * **        
         hex   4b3400    ; ** *  *  * **        
         hex   4b3400    ; ** *  *  * **        
         hex   433000    ; **    *    **        
         hex   7f3f00    ; *************        
         hex   2a1500    ;  * * * * * *         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   7e7f00    ;  *************       
         hex   166800    ;  ** *     * **       
         hex   166900    ;  ** *  *  * **       
         hex   166900    ;  ** *  *  * **       
         hex   066100    ;  **    *    **       
         hex   7e7f00    ;  *************       
         hex   542a00    ;   * * * * * *        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   7c7f01    ;   *************      
         hex   0c4201    ;   **    *    **      
         hex   2c5201    ;   ** *  *  * **      
         hex   2c5201    ;   ** *  *  * **      
         hex   2c5001    ;   ** *     * **      
         hex   7c7f01    ;   *************      
         hex   285500    ;    * * * * * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   787f03    ;    *************     
         hex   180403    ;    **    *    **     
         hex   582403    ;    ** *  *  * **     
         hex   582403    ;    ** *  *  * **     
         hex   582003    ;    ** *     * **     
         hex   787f03    ;    *************     
         hex   502a01    ;     * * * * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   707f07    ;     *************    
         hex   302206    ;     **  *   *  **    
         hex   302206    ;     **  *   *  **    
         hex   301406    ;     **   * *   **    
         hex   301406    ;     **   * *   **    
         hex   707f07    ;     *************    
         hex   502a05    ;     * * * * * * *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   607f0f    ;      *************   
         hex   60440c    ;      **  *   *  **   
         hex   60440c    ;      **  *   *  **   
         hex   60280c    ;      **   * *   **   
         hex   60280c    ;      **   * *   **   
         hex   607f0f    ;      *************   
         hex   20550a    ;      * * * * * * *   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   407f1f    ;       *************  
         hex   40051a    ;       ** *     * **  
         hex   40051a    ;       ** *     * **  
         hex   402118    ;       **    *    **  
         hex   402118    ;       **    *    **  
         hex   407f1f    ;       *************  
         hex   402a15    ;       * * * * * * *  
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #11
* Shift #0
         hex   000000    ; 
         hex   2a5500    ;  * * * * * * *       
         hex   024000    ;  *           *       
         hex   024000    ;  *           *       
         hex   524000    ;  *  * *      *       
         hex   524000    ;  *  * *      *       
         hex   024000    ;  *           *       
         hex   2a5500    ;  * * * * * * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   542a01    ;   * * * * * * *      
         hex   040001    ;   *           *      
         hex   040001    ;   *           *      
         hex   240101    ;   *  * *      *      
         hex   240101    ;   *  * *      *      
         hex   040001    ;   *           *      
         hex   542a01    ;   * * * * * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   285502    ;    * * * * * * *     
         hex   080002    ;    *           *     
         hex   080002    ;    *           *     
         hex   082802    ;    *      * *  *     
         hex   082802    ;    *      * *  *     
         hex   080002    ;    *           *     
         hex   285502    ;    * * * * * * *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   502a05    ;     * * * * * * *    
         hex   100004    ;     *           *    
         hex   100004    ;     *           *    
         hex   105004    ;     *      * *  *    
         hex   105004    ;     *      * *  *    
         hex   100004    ;     *           *    
         hex   502a05    ;     * * * * * * *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   20550a    ;      * * * * * * *   
         hex   202009    ;      *      * *  *   
         hex   202009    ;      *      * *  *   
         hex   200008    ;      *           *   
         hex   200008    ;      *           *   
         hex   200008    ;      *           *   
         hex   20550a    ;      * * * * * * *   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   402a15    ;       * * * * * * *  
         hex   404012    ;       *      * *  *  
         hex   404012    ;       *      * *  *  
         hex   400010    ;       *           *  
         hex   400010    ;       *           *  
         hex   400010    ;       *           *  
         hex   402a15    ;       * * * * * * *  
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   00552a    ;        * * * * * * * 
         hex   002920    ;        *  * *      * 
         hex   002920    ;        *  * *      * 
         hex   000120    ;        *           * 
         hex   000120    ;        *           * 
         hex   000120    ;        *           * 
         hex   00552a    ;        * * * * * * * 
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #12
* Shift #0
         hex   000000    ; 
         hex   000000    ;                      
         hex   000000    ;                      
         hex   200400    ;      *   *           
         hex   000100    ;        *             
         hex   200400    ;      *   *           
         hex   000000    ;                      
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   000000    ;                      
         hex   000000    ;                      
         hex   400800    ;       *   *          
         hex   000200    ;         *            
         hex   400800    ;       *   *          
         hex   000000    ;                      
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   205100    ;      * *   * *       
         hex   204000    ;      *       *       
         hex   205100    ;      * *   * *       
         hex   000400    ;          *           
         hex   205100    ;      * *   * *       
         hex   204000    ;      *       *       
         hex   205100    ;      * *   * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   402201    ;       * *   * *      
         hex   400001    ;       *       *      
         hex   402201    ;       * *   * *      
         hex   000800    ;           *          
         hex   402201    ;       * *   * *      
         hex   400001    ;       *       *      
         hex   402201    ;       * *   * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   20450a    ;      * * *   * * *   
         hex   000102    ;        *       *     
         hex   20450a    ;      * * *   * * *   
         hex   402a05    ;       * * * * * *    
         hex   20450a    ;      * * *   * * *   
         hex   000102    ;        *       *     
         hex   20450a    ;      * * *   * * *   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   400a15    ;       * * *   * * *  
         hex   000204    ;         *       *    
         hex   400a15    ;       * * *   * * *  
         hex   00550a    ;        * * * * * *   
         hex   400a15    ;       * * *   * * *  
         hex   000204    ;         *       *    
         hex   400a15    ;       * * *   * * *  
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   00152a    ;        * * *   * * * 
         hex   000408    ;          *       *   
         hex   000528    ;        * *       * * 
         hex   000210    ;         *         *  
         hex   000528    ;        * *       * * 
         hex   000408    ;          *       *   
         hex   00152a    ;        * * *   * * * 
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #13
* Shift #0
         hex   000000    ; 
         hex   700700    ;     ******           
         hex   400100    ;       **             
         hex   400100    ;       **             
         hex   580d00    ;    ** ** **          
         hex   700700    ;     ******           
         hex   600300    ;      ****            
         hex   400100    ;       **             
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   600f00    ;      ******          
         hex   000300    ;        **            
         hex   000300    ;        **            
         hex   301b00    ;     ** ** **         
         hex   600f00    ;      ******          
         hex   400700    ;       ****           
         hex   000300    ;        **            
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   401f00    ;       ******         
         hex   000600    ;         **           
         hex   306600    ;     **  **  **       
         hex   707600    ;     *** ** ***       
         hex   603f00    ;      ********        
         hex   401f00    ;       ******         
         hex   000f00    ;        ****          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   003f00    ;        ******        
         hex   000c00    ;          **          
         hex   604c01    ;      **  **  **      
         hex   606d01    ;      *** ** ***      
         hex   407f00    ;       ********       
         hex   003f00    ;        ******        
         hex   001e00    ;         ****         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   007e00    ;         ******       
         hex   003c00    ;          ****        
         hex   403d03    ;       ** **** **     
         hex   407f03    ;       **********     
         hex   007f01    ;        ********      
         hex   007e00    ;         ******       
         hex   003c00    ;          ****        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   007c01    ;          ******      
         hex   007800    ;           ****       
         hex   007b06    ;        ** **** **    
         hex   007f07    ;        **********    
         hex   007e03    ;         ********     
         hex   007c01    ;          ******      
         hex   007800    ;           ****       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   000c06    ;          **    **    
         hex   001001    ;            *  *      
         hex   00160d    ;         ** *  * **   
         hex   001e0f    ;         ****  ****   
         hex   000c06    ;          **    **    
         hex   001803    ;           **  **     
         hex   007001    ;            ****      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #14
* Shift #0
         hex   000000    ; 
         hex   040800    ;   *       *          
         hex   052800    ; * *       * *        
         hex   152a00    ; * * *   * * *        
         hex   552a00    ; * * * * * * *        
         hex   5d2e00    ; * *** * *** *        
         hex   552a00    ; * * * * * * *        
         hex   540a00    ;   * * * * *          
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   081000    ;    *       *         
         hex   0a5000    ;  * *       * *       
         hex   2a5400    ;  * * *   * * *       
         hex   2a5500    ;  * * * * * * *       
         hex   3a5d00    ;  * *** * *** *       
         hex   2a5500    ;  * * * * * * *       
         hex   281500    ;    * * * * *         
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   102000    ;     *       *        
         hex   142001    ;   * *       * *      
         hex   542801    ;   * * *   * * *      
         hex   542a01    ;   * * * * * * *      
         hex   5c2e01    ;   *** * *** * *      
         hex   542a01    ;   * * * * * * *      
         hex   502a00    ;     * * * * *        
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   204000    ;      *       *       
         hex   284002    ;    * *       * *     
         hex   285102    ;    * * *   * * *     
         hex   285502    ;    * * * * * * *     
         hex   385d02    ;    *** * *** * *     
         hex   285502    ;    * * * * * * *     
         hex   205500    ;      * * * * *       
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   400001    ;       *       *      
         hex   500005    ;     * *       * *    
         hex   502205    ;     * * *   * * *    
         hex   703a05    ;     *** * *** * *    
         hex   502a05    ;     * * * * * * *    
         hex   502a05    ;     * * * * * * *    
         hex   402a01    ;       * * * * *      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   000102    ;        *       *     
         hex   20010a    ;      * *       * *   
         hex   20450a    ;      * * *   * * *   
         hex   60750a    ;      *** * *** * *   
         hex   20550a    ;      * * * * * * *   
         hex   20550a    ;      * * * * * * *   
         hex   005502    ;        * * * * *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   000204    ;         *       *    
         hex   400214    ;       * *       * *  
         hex   400a15    ;       * * *   * * *  
         hex   402e17    ;       * *** * *** *  
         hex   402a15    ;       * * * * * * *  
         hex   402a15    ;       * * * * * * *  
         hex   002a05    ;         * * * * *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
* Entity image #15
* Shift #0
         hex   000000    ; 
         hex   000000    ;                      
         hex   200000    ;      *               
         hex   680200    ;    * ** *            
         hex   200100    ;      * *             
         hex   100000    ;     *                
         hex   000000    ;                      
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #1
         hex   000000    ; 
         hex   000000    ;                      
         hex   400000    ;       *              
         hex   500500    ;     * ** *           
         hex   400200    ;       * *            
         hex   200000    ;      *               
         hex   000000    ;                      
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #2
         hex   000000    ; 
         hex   300900    ;     ** *  *          
         hex   401500    ;       ** * *         
         hex   302a00    ;     **  * * *        
         hex   480500    ;    *  ** *           
         hex   201900    ;      * *  **         
         hex   100a00    ;     *   * *          
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #3
         hex   000000    ; 
         hex   601200    ;      ** *  *         
         hex   002b00    ;        ** * *        
         hex   605400    ;      **  * * *       
         hex   100b00    ;     *  ** *          
         hex   403200    ;       * *  **        
         hex   201400    ;      *   * *         
         hex   000000    ;                      
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #4
         hex   000000    ; 
         hex   502501    ;     * ** *  * *      
         hex   005604    ;         ** * *  *    
         hex   202101    ;      * *    * *      
         hex   000200    ;         *            
         hex   206502    ;      * * *  ** *     
         hex   402800    ;       *   * *        
         hex   000902    ;        *  *    *     
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #5
         hex   000000    ; 
         hex   204b02    ;      * ** *  * *     
         hex   002c09    ;          ** * *  *   
         hex   404202    ;       * *    * *     
         hex   000400    ;          *           
         hex   404a05    ;       * * *  ** *    
         hex   005100    ;        *   * *       
         hex   001204    ;         *  *    *    
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
* Shift #6
         hex   000000    ; 
         hex   40160d    ;       * ** *  * **   
         hex   000a12    ;         * *    *  *  
         hex   000504    ;        * *      *    
         hex   000204    ;         *       *    
         hex   00050a    ;        * *     * *   
         hex   003603    ;         ** ** **     
         hex   002408    ;          *  *    *   
         hex   000000    ; 
         ds    5 ; pad to 32 bytes
         ds    32 ; pad to page boundary
